### ISSUE TITLE
ドメインモデルの用語集書き直し。

### ISSUE THREAD

**Issue by acceplexity** [Mori-Nasite/HogeHogeQuest#18]
ドメインモデルの用語集を確定させる。担当は森さん。12/24迄。

**Comment by nobutaka-w** [comment]
slackにて用語集が確定したので、issueを閉じます。
また、Wikiにもその内容を反映させました。

**Comment by acceplexity** [comment]
用語集確定までの流れ

Mori-Nasite
とりあえずの用語集です
変更点として、ライブラリを削除し、
入力インターフェースと出力インターフェースに関しては入力インターフェースがキーボードという抽象度なのに対し出力インターフェースがWPFの画面となっていて対応していなかったのでディスプレイとしました
また、戦闘ゲームシーンの処理の一部をプレイヤー(自キャラ)とエネミーに分散しました
他にもフィールドやミュージック等を用意しようかと思いましたが関数1つで実装が済んでしまうためわざわざ用意しなくてもいいかなと思いました
まだ何か練足りない気がしないでもないですがとりあえずはこんな感じです
あとWPF＝ゲームエンジンでいろいろ分かりづらかったのでゲームウインドウとしました

acceplexity
@nasite お疲れ様です。抽象度を揃えてくれたのと混乱の元になっていた用語の整理ができたみたいでよかったです。ところで、この下の工程でモデル図、ロバストネス図を作成するのにキーボードのどのボタンみたいなことを書かないといけないような話じゃなかったかなと思うんですがどうでしたっけ？

nasite
書くみたいなことは言ってました
具体的にはユースケースなどで他のグループで「なんとかボタンを押すと～する」の部分と同じような書き方になると思います
今のところ決まっているキーは
上下カーソルキーで選択、エンターキーで決定です

acceolexity
図と用語集の言葉を一致させないといけないはずなので使う予定のキーを用語集にも入れておいてもらえますか

nasite 
追加しました

naoki-yo
@nobutaka-w 用語集が確定したようなので確認してissueを閉じてください。とりあえず、図の作成は12/30までにしましょう。描き直しが多くなると時間が足りなくなるので過去の遺産をもとにじゅうぶん練ってから投稿してください。
