### ISSUE TITLE
ドメインモデル図とロバストネス図の書き直し

### ISSUE THREAD

**Issue by nobutaka-w** [Mori-Nasite/HogeHogeQuest#19]
用語集に基づくドメインモデル図とロバストネス図の作成を行う。
期限は12月30日。
担当は若松。

**Comment by acceplexity** [comment]
確認しました。現在、修正中。

**Comment by acceplexity** [comment]
修正が済んだので閉じます。

**Comment by acceplexity** [comment]
若松
https://files.slack.com/files-pri/T0FQJAXJL-F0HF6QH19/_________________________12_30_2_20.jpg
ドメインモデル図を書き直したので上げます。
https://files.slack.com/files-pri/T0FQJAXJL-F0HF6R60K/______________________12_30_02_16.jpg
また、ロバストネス図も描いてみました。
おかしい点があればご指摘をお願いします。
