### ISSUE TITLE
ゲームの仕様を詳しく書く。

### ISSUE THREAD

**Issue by acceplexity** [Mori-Nasite/HogeHogeQuest#21]

**Comment by acceplexity** [comment]
指摘された通りどういうゲームなのかがわかりにくいのでゲーム仕様を詳しく書きます。

**Comment by acceplexity** [comment]
担当は横山

**Comment by acceplexity** [comment]
担当を変えます。若松&藤井

**Comment by nobutaka-w** [comment]
戦闘開始時に、
　画面上にエネミーの画像とHPを表示する。
　画面の下の位置にはコマンドウィンドウを表示する。
　　コマンドウインドウには、戦うなどのコマンドとプレイヤー名とプレイヤーのHPを表示する。この状態を入力待ち状態と呼ぶ。
上キー、下キーを入力した場合、コマンドウインドウのカーソルを対応する方向の項目に移動してから入力待ち状態に戻る。
エンターキーを入力した場合、選択されているコマンドに応じてエネミーへのダメージ処理を行う。
　ダメージ処理後、エネミーのHPが0になった場合はゲームクリア処理を行う。
　エネミーのHPが1以上残っている場合はエネミーのターンに移行する。
　　エネミーのターン終了後、プレイヤーのコマンド入力待ち状態に戻る。

といった感じで戦闘シーンイメージの説明文を書いてみました。
何かおかしい部分がありましたらご指摘お願いします。

**Comment by nobutaka-w** [comment]
ユースケース分析を以下のように書き直しました。

基本コース：
ユーザーはキーボードから上キーor下キーorエンターキーを入力する。
上or下キーが入力された場合はゲームウインドウのカーソルを移動させる。
エンターキーが押された場合は選択されたコマンドを認識して、コマンド別の処理を行う。
「戦う」を選択した場合、以下の3つの処理を行う。
1.エフェクトを表示してエネミーのHPを減らす処理を行う。
2.エネミーのHPをゲームウインドウに反映させる処理を行う。
3.エネミーのターンへの以降処理
エネミーのターンに以降した後、以下の3つの処理を行う。
1.エフェクトを表示してプレイヤーのHPを減らす処理を行う。
2.プレイヤーのHPをゲームウインドウに反映させる処理を行う。
3.アクターのコマンド入力待ち状態に移行する。

代替コース：
キーボードからの指定されていないキー入力やコマンド選択は無視する。

これでよければ、確認した後にcloseお願いします。

**Comment by acceplexity** [comment]
確認しましたのでcloseします。
