### ISSUE TITLE
シーケンス図を書き直す。

### ISSUE THREAD

**Issue by fujii-h** [Mori-Nasite/HogeHogeQuest#23]
修正箇所が生じたため。

**Comment by acceplexity** [comment]
担当は森。

**Comment by fujii-h** [comment]
![sequence_fig_mod3or4](https://cloud.githubusercontent.com/assets/12648176/12318383/1b192518-badd-11e5-9da4-9126b1fce174.png)
issue内画像アップロードのテストも兼ねて現状のシーケンス図を提示。
※修正は森さん。

**Comment by acceplexity** [comment]
Wikiに反映したので閉じます。
