### ISSUE TITLE
開発環境の導入と確認。

### ISSUE THREAD

**Issue by fujii-h** [Mori-Nasite/HogeHogeQuest#25]
Visual Studioの導入と現状までのコードが動作するか確認する。
担当：Moriさん以外。
確認：森さん。

**Comment by acceplexity** [comment]
横山、動作確認終了。
![](https://files.slack.com/files-pri/T0FQJAXJL-F0JEA48JV/____________________________2016-01-14_20.29.59.png)
藤井、動作確認終了。
![](https://files.slack.com/files-pri/T0FQJAXJL-F0JEG6Z89/hogehoge_fujii-h.png)

それぞれscreenshotを添付。

**Comment by Mori-Nasite** [comment]
確認しましたので閉じます
