### ISSUE TITLE
マイルストーンの内容を確定する。

### ISSUE THREAD

**Issue by fujii-h** [Mori-Nasite/HogeHogeQuest#28]
マイルストーンの内容を確定し，メンバ全員の同意が得られ次第closeする．

**Comment by acceplexity** [comment]
マイルストーンの自分担当分を上げます。

エフェクトを表示する。同時に、プレイヤーのHPの計算処理。
計算後のプレイヤーのHPをゲームウインドウに表示。
アクターのコマンド入力待ち状態に移行する。

**Comment by nobutaka-w** [comment]
マイルストーンの内容ですが、僕の担当部分の内容は以下のようになりました。

・プレイヤーによるキーボードからの入力を検知する処理を作る
・入力されたキーがどのキーなのかを認識する処理を作る
・上キーor下キーが入力されたときに、ゲームウインドウのカーソルを移動させる処理を作る
・エンターキーが入力されたときに、選択されているコマンドを認識し、コマンド別の処理を開始する処理を作る

**Comment by nobutaka-w** [comment]
代替コースのマイルストーンは以下の内容でお願いします。
・キーボードからの指定されていないキー入力やコマンド選択は無視する。

**Comment by fujii-h** [comment]
プレイヤーのターンに関する処理のマイルストーンです。

マイルストーン「コーディング」直下
　・マイルストーン「プレイヤーターンにおいて、「戦う」を選択した場合の処理の実装。」
　・・issue1「攻撃のエフェクトを表示し、エネミーのHPを減らす処理に関する処理。」
　・・issue2「プレイヤーの攻撃による、エネミーのHP減少をGUI上に反映させる処理。」
　・・issue3「エネミーのターンへ移行するための処理。」

**Comment by acceplexity** [comment]
作業規模はＯＫという評価。

**Comment by acceplexity** [comment]
マイルストーンを登録。その中にissueを登録し、assigneeも指定。

**Comment by acceplexity** [comment]
確定したので閉じます。
