### ISSUE TITLE
機能要求の作成

### ISSUE THREAD

**Issue by acceplexity** [Mori-Nasite/HogeHogeQuest#4]
機能要求の作成を行います。

**Comment by nobutaka-w** [comment]
プラットドームはWindowsのみ。
フィールドの切り替え、建物に入る、戦闘に入る、戦闘に移行する際に必要な画面の切り替え機能。
BGMの切り替え機能。設定画面、セーブ画面では切り替わらない。ロードが終わった後に切り替わるなど。
テキストの表示に関する機能。（表示されている文字の上書きなど）
会話機能、会話における分岐機能（はい、いいえ等）
物体との接触判定に関する機能（マップ外に出ない、建物・キャラクタとの接触など）
キーボードからの入力を受け付ける機能
アスペクト比は固定
画面サイズは可変（画面を等倍することで対応する）

シーン
優先順位が高い順に
・戦闘画面
・ゲームオーバー
・ゲームクリア画面
・タイトル
・探索画面
・アイテム、装備選択画面
・会話画面
・設定画面
が必要。

**Comment by acceplexity** [comment]
重複＆書き直しを行ったため閉じます。
