### ISSUE TITLE
#機能要求を書く

### ISSUE THREAD

**Issue by acceplexity** [Mori-Nasite/HogeHogeQuest#7]
機能要求を書き終えて、みんなの了承が得られたら閉じる。

**Comment by nobutaka-w** [comment]
機能要求は
・入力インターフェースを用いてコマンドを選択できる。また、出力インターフェースを用いてその変更が確認できる。
1パソコンのキーボードを入力インターフェースとして、出力にWPFの画面を用いる。
2ユーザーが選択したコマンドに応じたアクションが画面上に出力される。

となりました。
僕はこれでいいと思います。

**Comment by acceplexity** [comment]
機能要求作成終わりましたので閉じてください。

**Comment by fujii-h** [comment]
確認しました。
