### ISSUE TITLE
#ドメインモデル作成

### ISSUE THREAD

**Issue by acceplexity** [Mori-Nasite/HogeHogeQuest#8]
ドメインモデルを作成し、みんなの了承が得られたら閉じる。

**Comment by nobutaka-w** [comment]
![2](https://cloud.githubusercontent.com/assets/15243580/11775278/c56940fe-a280-11e5-97b5-cc6c11a4c77b.jpg)
ドメインモデル図を作成してみました。
Slackにも同じ画像を上げています。
おかしい点などありましたらご指摘をお願いします。

**Comment by nobutaka-w** [comment]
![5](https://cloud.githubusercontent.com/assets/15243580/11835431/cec524c8-a416-11e5-8f8e-e14f4efd5c49.jpg)
ドメインモデル図を修正しました。
こんな感じでいいなら確認の後にCloseしてください。

**Comment by nobutaka-w** [comment]
確認が取れたのでCloseします。
